### ISSUE TITLE
accepting PRs?

### ISSUE THREAD

**Issue by zhuker** [webrtc-for-the-curious/webrtc-for-the-curious#1]
;)

**Comment by Sean-Der** [comment]
@zhuker YES PLEASE, 100% send them over! Also I would love any feedback you have, please be hyper-critical I just want this to be a great community resource :)

The two big decisions I have made that aren't documented
* I have a friend doing illustrations. It is going to feel like a 'medieval manuscript' but with a humorous bend. 
* I want to publish this, and will need to figure out the money part.. 

I want to pay for the illustrations. If you (or anyone else) plan on doing significant contributions I would love to pay as well. I going to donate my share. I would rather see more outside contributions than make money.

I am purposely decoupling this from Pion and not making money so I can get larger community buy-in. Would be great to see other WebRTC projects get involved.

**Comment by zhuker** [comment]
100%

**Comment by Sean-Der** [comment]
I am closing since @zhuker is working on the book :)

I am going to create an issue to split up tasks better.

**Comment by zhuker** [comment]
Cool
