### ISSUE TITLE
Chapter Ownership

### ISSUE THREAD

**Issue by Sean-Der** [webrtc-for-the-curious/webrtc-for-the-curious#10]
These aren’t hard assignments! Maybe just a good start to find out people’s availability/interest. Totally understand if people don’t actually have the bandwidth. A rough draft is also better then nothing!

* Data Communication - @enobufs 
* Media Communication - @zhuker 
* Applied WebRTC - @leewardbound

@tQsW what interests you the most? If you like networking that chapter still needs massive improvements :)

But w/e people feel passionate about is what they should do. That is how you get quality IMO.

**Comment by leewardbound** [comment]
Thanks for the tag! I am trying to make time to get to this soon :) I am
excited to help!

**Comment by tQsW** [comment]
I’ll try to do a round of editing of the connection part and can also look into a skeleton on the congestion and rate control.

**Comment by Sean-Der** [comment]
@zhuker Have you written up anything on RTP yet?

@tQsW The intro to RTP might be really cool! People will really love how flexible it is compared to a container (FLV)

Then I would LOVE to get into 

* error correction (FEC and NACK) 
* handling latency (jitterbuffer)
* congestion control
* multicast?
* lots more stuff I am ignorant of :)

So excited to have you involved
