### ISSUE TITLE
Broken path to image

### ISSUE THREAD

**Issue by dontcallmedom** [webrtc-for-the-curious/webrtc-for-the-curious#124]
https://webrtcforthecurious.com/docs/06-media-communication/ is supposed to embed https://webrtcforthecurious.com/images/06-frame-types.png but instead links to https://webrtcforthecurious.com/docs/images/06-frame-types.png

I would have provided a pull request but since the image appears correctly in https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/blob/master/content/docs/06-media-communication.md, I figured this may need more contextual awareness than I have

**Comment by Sean-Der** [comment]
Hey @dontcallmedom, thank so you much for reporting this will check it out.

I am really honored you read the book! I would love your perspective/feedback on the book. With everyone you teach/inform about WebRTC does the book hit the points that would be helpful?

When writing this I thought of it like a companion piece to webrtc-pc. For developers that know how to use that API, but I starting to wonder what is actually happening behind the scenes.

**Comment by dontcallmedom** [comment]
I haven't read it fully yet, but I liked a lot what I read :) I'll try to provide more structured feedback when I get a chance to do a more in-depth review

**Comment by mogren** [comment]
This is my fault, and comes from #113 where we tried to get images working with pandoc as well as Hugo. It seems like the gh-pages branch doesn't get the symlink. I'll add a step to the workflow to fix it. Probably we will want to have one image folder per translation.
