### ISSUE TITLE
[Feedback] Not in the same network

### ISSUE THREAD

**Issue by hiroyuki-sato** [webrtc-for-the-curious/webrtc-for-the-curious#130]
Thank you for creating great documents. It's very useful.

https://webrtcforthecurious.com/docs/03-connecting/#not-in-the-same-network

This section says.

> For the hosts in the same network it is very easy to connect. Communication between 192.168.0.1 -> 192.168.0.2 is easy to do! These two hosts can connect to each other without any outside help.

But this image doesn't show `192.168.0.2`

Current

![](https://webrtcforthecurious.com/docs/images/03-nat-mapping.png)

Correct image?

![](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/blob/master/content/docs/images/03-two-networks.png?raw=true)

Best regards.

**Comment by mogren** [comment]
Thanks for reporting @hiroyuki-sato, you are completely right! Fix in #131

**Comment by hiroyuki-sato** [comment]
Hello, @mogren Thank you for your reply. I create #132 for Japanese content.
I'll close this issue after PRs merge.

**Comment by hiroyuki-sato** [comment]
All language status. (Just for future reference)

| lang     | status                     |
|----------|----------------------------|
| original | Done #131                       |
| ja       | Done #132                       |
| tr       | no content (only TODO word)|
| fa       | no content                 |
| zh-cn    | [already fixed](https://webrtcforthecurious.com/zh/docs/03-connecting/#不在同一个网络中) |
