### ISSUE TITLE
Bug:  [Security 101]-[Nonce]-[By using a nonce you can get different input]

### ISSUE THREAD

**Issue by katepangLiu** [webrtc-for-the-curious/webrtc-for-the-curious#195]
## original:
A nonce is an additional input to a cipher. This is used so that you can get different output from the cipher, even if you are encrypting the same message multiple times.

If you encrypt the same message 10 times, the cipher will give you the same ciphertext 10 times. **By using a nonce you can get different input**, while still using the same key. It is important you use a different nonce for each message! Otherwise, it negates much of the value.

## expectation:
By using a nonce you can get different **output**.

**Comment by mogren** [comment]
Fixed in #196
