### ISSUE TITLE
TLS is used to secure communication over TCP, not just HTTP

### ISSUE THREAD

**Issue by katepangLiu** [webrtc-for-the-curious/webrtc-for-the-curious#230]

**Comment by mogren** [comment]
Hmm, I'm not sure about this... From [Wikipedia on TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security):

>The TLS protocol aims primarily to provide privacy and data integrity between two or more communicating computer applications. It runs in the application layer and is itself composed of two layers: the TLS record and the TLS handshake protocols.

and

> TLS and SSL do not fit neatly into any single layer of the OSI model or the TCP/IP model. TLS runs "on top of some reliable transport protocol (e.g., TCP)," which would imply that it is above the transport layer. It serves encryption to higher layers, which is normally the function of the presentation layer. However, applications generally use TLS as if it were a transport layer, even though applications using TLS must actively control initiating TLS handshakes and handling of exchanged authentication certificates.

In short, saying that TLS puts the S in HTTPS seems about right. 😄

**Comment by katepangLiu** [comment]
> Hmm, I'm not sure about this... From [Wikipedia on TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security):
> 
> > The TLS protocol aims primarily to provide privacy and data integrity between two or more communicating computer applications. It runs in the application layer and is itself composed of two layers: the TLS record and the TLS handshake protocols.
> 
> and
> 
> > TLS and SSL do not fit neatly into any single layer of the OSI model or the TCP/IP model. TLS runs "on top of some reliable transport protocol (e.g., TCP)," which would imply that it is above the transport layer. It serves encryption to higher layers, which is normally the function of the presentation layer. However, applications generally use TLS as if it were a transport layer, even though applications using TLS must actively control initiating TLS handshakes and handling of exchanged authentication certificates.
> 
> In short, saying that TLS puts the S in HTTPS seems about right. 😄

Of course it's right. 
But if we want to say "DTLS is just TLS over UDP", maybe "TLS is securing over TCP" is better in here.
It's all right, nothing serious.

**Comment by mogren** [comment]
@katepangLiu I still think you have a point though, this section isn't clear enough. I think the `The second protocol is SRTP (Secure Real-time Transport Protocol).` sentence is the problematic point. Maybe it should say 'The corresponding protocol for UDP traffic is SRTP (Secure Real-time Transport Protocol).`?

**Comment by katepangLiu** [comment]
> @katepangLiu I still think you have a point though, this section isn't clear enough. I think the `The second protocol is SRTP (Secure Real-time Transport Protocol).` sentence is the problematic point. Maybe it should say `The corresponding protocol for UDP traffic is SRTP (Secure Real-time Transport Protocol).`?

Here the `second` means:
```
Two protocol:
1. SRTP
2. DTLS
```

**Comment by katepangLiu** [comment]
> @katepangLiu I still think you have a point though, this section isn't clear enough. I think the `The second protocol is SRTP (Secure Real-time Transport Protocol).` sentence is the problematic point. Maybe it should say `The corresponding protocol for UDP traffic is SRTP (Secure Real-time Transport Protocol).`?



> > @katepangLiu I still think you have a point though, this section isn't clear enough. I think the `The second protocol is SRTP (Secure Real-time Transport Protocol).` sentence is the problematic point. Maybe it should say `The corresponding protocol for UDP traffic is SRTP (Secure Real-time Transport Protocol).`?
> 
> Here the `second` means:
> 
> ```
> Two protocol:
> 1. SRTP
> 2. DTLS
> ```

Maybe we can use some makedown syntax here to make the architection more clear.
