### ISSUE TITLE
"Generating a Bandwidth Estimate" glosses over important elements of bandwidth estimation

### ISSUE THREAD

**Issue by gcolten** [webrtc-for-the-curious/webrtc-for-the-curious#242]
Regarding: "Generating a Bandwidth Estimate" in section 6.

While packet loss is _one_ indicator of network congestion, Google Congestion Control uses another measure that may have a much larger impact on advertised available bitrates.

Without needing to go too far into the weeds, I think it's worth calling out that GCC's usage of a Kalman filter is to make accurate estimations of inter-packet arrival delays. GCC measures the differences in arrival times of each frame, and from that variation infers whether or not the network is congested. Increases in inter-packet arrival times (after controlling for the variation in frame size in bytes) suggest that the network is increasingly queuing up packets on a congested link. If that inferred congestion increases sufficiently (sufficiently-large time increases over a long-enough measurement window), GCC will reduce the advertised incoming bitrate.

If that is too much detail to add for this section, that's alright. It may suffice to add a superficial description about how GCC attempts to estimate network congestion and may reduce incoming bitrate advertisements even in the absence of (appreciable) packet loss.

**Comment by Sean-Der** [comment]
I would love too see that @gcolten! I don't think that would be too much detail at all.

We talk about Packet Loss, Transit Time and ECN [here](https://webrtcforthecurious.com/docs/05-real-time-networking/#detecting-congestion) a little bit. Maybe we can link users back.

Then in the `Generating a Bandwidth Estimate` section we can talk about the Kalman filter and what it does given certain inputs?

@mengelbart is working on a Go implementation and understands it much better then me.

**Comment by mengelbart** [comment]
I agree that it would be nice to have these details documented and I could help write or review this section!

**Comment by gcolten** [comment]
The way I would write it, I'd shuffle the layout for the last two sections (Communicating Network Status and Generating a Bandwidth Estimate).

I started some progress on how I (taking some editorial liberties) would organize these sections. Still haven't gotten to actually adding details for GCC yet...

[My WIP draft](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/pull/244)

Let me know if you do (or don't) like the direction I'm heading.
