### ISSUE TITLE
case inconsistency: addicecandidate versus addIceCandidate 

### ISSUE THREAD

**Issue by ScottKell** [webrtc-for-the-curious/webrtc-for-the-curious#25]
TIny thing... but in section "How does WebRTC (the API) work", lowercase addicecandidate and mixed case addIceCandidate are both used.  Should be mixed case

**Comment by Sean-Der** [comment]
Nice catch! You up for making a PR for this? If not I can grab :)

**Comment by ScottKell** [comment]
Happy to.  I tried to branch off master with change to submit a PR.  (gitflow) Could not push that branch.  403.  DO I need you to grant privs?  Or another way I should submit PR?

**Comment by Sean-Der** [comment]
Hey @ScottKell sorry for the delay.

I would fork this repo, and make the change in your master branch. Then you can submit a PR from there!

If you are still having trouble feel free to share a diff and I will commit with your email :)

**Comment by threeplanetssoftware** [comment]
This was fixed in 21a6cdaeb5121c29504b603cc0c82bdaedd4b7cd, suggest closing the issue.

**Comment by Sean-Der** [comment]
:+1: thanks for catching this @threeplanetssoftware
