### ISSUE TITLE
invite @katepangLiu  as the maintainer

### ISSUE THREAD

**Issue by hiroyuki-sato** [webrtc-for-the-curious/webrtc-for-the-curious#266]
I would like to invite @katepangLiu  as the maintainer of this project.
@katepangLiu [helping](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/pulls?q=is%3Apr+author%3AkatepangLiu+) us to support Chinese translation.
(I can't read Chinese. So, It is hard to comment about a Chinese translation. And also, we receive many requests about the Chinese translation).

@Sean-Der @mogren and @voluntas, What do you think?

**Comment by mogren** [comment]
Definitely! I thought he was already. Please add him. 😄

**Comment by hiroyuki-sato** [comment]
@mogren Thanks! I invited @katepangLiu as the maintainer.
@katepangLiu, Could you check the invite e-mail?

**Comment by katepangLiu** [comment]
Thanks @hiroyuki-sato .

**Comment by hiroyuki-sato** [comment]
@katepangLiu Welcome to Webrtc for the curious!! Please check the Chinese translation.
Please let me know if you need to double-check.
