### ISSUE TITLE
PDF/EPUB Version

### ISSUE THREAD

**Issue by kevindumanoir** [webrtc-for-the-curious/webrtc-for-the-curious#27]
I wanted to read this book on my reader, but then realized there was no PDF/EPUB version. Is it planned?

**Comment by banagale** [comment]
I was also looking for an epub version.

It looks like this could be done with pandadoc. 

Here are some rough copies of the current master in pdf and epub:
[WebRTC for the Curious.pdf](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/files/5147516/WebRTC.for.the.Curious.pdf)
[WebRTC for the Curious.epub.zip](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/files/5147518/WebRTC.for.the.Curious.epub.zip)

**Comment by Sean-Der** [comment]
That is awesome! Thanks for doing that @banagale 

Would you mind sharing how you did it/share a script? I will add it to the `GitHub Actions` and throw a link in the index.html and README.md :)

**Comment by banagale** [comment]
Sure--I wish I could say I had a cool script, but I actually just searched the web for markup to pdf and markup to epub. There are some sites that let you drag and drop. I had to assemble the pdf into one document with acrobat though.

**Comment by davenewham** [comment]
Seems like pandoc would be a good candidate for doing this in Actions?

**Comment by soolaugust** [comment]
I agree with @davenewham , pandoc seems to be a good candidate. Maybe refet to https://github.com/pandoc/pandoc-action-example/blob/master/.github/workflows/advanced.yml to generate pdf or epub version. I refer to this to generate pdf version successfully, but not as expect. maybe need more working on learning pandoc. If anyone works on this, hope my following experience would be helpful.

Commit: https://github.com/soolaugust/webrtc-for-the-curious/commit/10a6233603c6fe0950123b69d0ffd4d12b30f82f
Generated artifact: https://github.com/soolaugust/webrtc-for-the-curious/actions/runs/233871430

**Comment by threeplanetssoftware** [comment]
This seems incredibly useful and I'm going to try to poke at it. If someone else gets it first, no hard feelings!
