### ISSUE TITLE
I want to help you with book translation in Russian as a "individual"

### ISSUE THREAD

**Issue by coldSeattle** [webrtc-for-the-curious/webrtc-for-the-curious#274]
I think I got inspired that work on the book and I want to make translate the book in Russian for the people who is not knowing already translated langs well goodand get attention at webRTC, and not try to translating a text for understanding it deep dive.

**Comment by katepangLiu** [comment]
That would be nice. Thanks @coldSeattle .

**Comment by coldSeattle** [comment]
How I can contribute for the translation?

**Comment by katepangLiu** [comment]
I think you can fork this repo, then create  a dir, such as `content.ro` , then fill files into the dir, just as other language versions.

**Comment by mogren** [comment]
Like @katepangLiu said, feel free to just make a new translation folder and add it in [config.toml[(https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/blob/master/config.toml#L34-L38). No need to translate all of it at once, feel free to add chapter by chapter, or even parts of chapters at a time. 😄

**Comment by coldSeattle** [comment]
okay guys, thanks
