### ISSUE TITLE
Chapter on congestion control

### ISSUE THREAD

**Issue by disa6302** [webrtc-for-the-curious/webrtc-for-the-curious#36]
Not sure if this is going to be part of any chapter, but I think we should have a dedicated chapter on this.

**Comment by Sean-Der** [comment]
Yea!

So right now we are going to have two dedicated places that about Congestion Control `SCTP` and `RTP`.

I am wondering if we should have a general 'These are all the bad things that can happen on the network'.

**Comment by Sean-Der** [comment]
Done! Chapter 5 is 'Real-time networking'

It talks about Congestion Control in the abstract. The Media+Data chapters then talk about actual implementation details.
