### ISSUE TITLE
Book Pitch/Ethos

### ISSUE THREAD

**Issue by Sean-Der** [webrtc-for-the-curious/webrtc-for-the-curious#5]
These are the guiding principles/ideas I have been working off of. Feel free to add more and discuss :)

### The book is designed for multiple reads

We should write the book so that you can get value even if you don’t understand everything. Each chapter should be self contained and ramp up in difficulty. If you don’t understand ICE the RTP section should still be useful.

* What is being solved (Packet loss)
* How is it solved (NACK)
* How do they actually work (Deep dive)

### Target Audiences 

* Web Developers who don’t even know what WebRTC solves
* Someone who builds with WebRTC but wants to know more
* Established Developer who needs help debugging 
* WebRTC implementor who needs a rough idea on one piece.

### Communicate our love of RTC
This is hard to do, but I hope we can genuinely get people excited. I think showing history and use cases will help a lot.

### Vendor Agnostic
It will be important for getting others involved. I hope we can make something that other WebRTC projects will feel comfortable sharing with their community.

**Comment by Sean-Der** [comment]
@zhuker @enobufs

**Comment by disa6302** [comment]
Amazing initiative! Would love to pitch in!

**Comment by Sean-Der** [comment]
This is all captured in the intro now!
