### ISSUE TITLE
Chapter on Data Communication has duplicate answer

### ISSUE THREAD

**Issue by MrRightC** [webrtc-for-the-curious/webrtc-for-the-curious#56]
Please see the screenshot，the answer to ***Question: How do I know if I am sending too much？*** is incorrect.
<img width="1143" alt="duplicateAnswer" src="https://user-images.githubusercontent.com/25995173/96531571-8cc7fb80-12bc-11eb-8bec-15f69ed46d03.png">

**Comment by mogren** [comment]
Looks like this issue can be closed, thanks for opening it in the first place!
