### ISSUE TITLE
Incomprehensible sentence, please explain

### ISSUE THREAD

**Issue by losojesper** [webrtc-for-the-curious/webrtc-for-the-curious#59]
This is the part I am really interested in and I can't wrap my head around this sentence. Please help!

Look here https://webrtcforthecurious.com/docs/03-connecting/#turn in the second paragraph
"TURN uses a dedicated server. This server acts as a proxy for a client. The client connects to a TURN Server and creates an Allocation. **By creating an Allocation a client gets a temporary IP/Port/Protocol that can send into to get traffic back to the client.** This new listener is known as the Relayed Transport Address. Think of it as a forwarding address, you give this out so others can send you traffic via TURN! For each peer you give the Relay Transport Address to, you must create a Permission to allow communication with you."

The bold part seems like an invalid sentence and I can't understand what the author meant.

**Comment by darkvertex** [comment]
I didn't write this sentence and while it is dense, grammatically, it looks correct to me.

What the bold part means is that when using TURN, the WebRTC client creates a TURN "_Allocation_", which is really just a sort of reserved location (a temporary IP and port specific to your ICE connection at that moment in time) that other peers can reach you through.

As the sentence afterwards implies, TURN acts as a relay, transmitting your traffic through it to the other peer. The other peers connect to the TURN's allocation relay, which then relays traffic to your client.

STUN, on the other hand, does not relay traffic through it; it only helps two peers "discover" each other through the public Internet, but once the connection is established, with STUN the traffic is peer-to-peer. With TURN, traffic is actually peer -to-> TURN -to> peer.

Is it clearer now? Did my explanation help?

**Comment by JayLow001** [comment]
Great explanation, thanks!

Just to make sure I get this correctly, could the bold part be rewritten like so:

By creating an Allocation a client gets a temporary IP/Port/Protocol that others can use to send traffic back to that same client.

This implies that traffic is one-way for this allocation. Is that so or can packets flow both ways?

Really appreciate the help!

Ps. I still think this "...that can send into to get..." part is really wierd. But I am not a native speaker...

**Comment by darkvertex** [comment]
> _This implies that traffic is one-way for this allocation. Is that so or can packets flow both ways?_

Both ways. TURN relays traffic and acts as a middleman, effectively passing packets to and from it, to either client.

**Comment by JayLow001** [comment]
Ok, thank you so very much, sir, for taking this time to clarify this for me!

**Comment by mogren** [comment]
@losojesper I edited the sentence, hope it makes more sense now.

**Comment by losojesper** [comment]
Great!
