### ISSUE TITLE
epub can not be read on iOS Books app

### ISSUE THREAD

**Issue by simevo** [webrtc-for-the-curious/webrtc-for-the-curious#61]
only the summary is visible; turning pages to the first actual content page or clicking on the 1st chapter ("Who is this book for") shows this:
![image](https://user-images.githubusercontent.com/8254819/101281683-bc7d8500-37d0-11eb-91fa-9ca07e4ca866.png)

the error is:
```
This page contains the following errors:

error on line 11 at column 92: Attribute data-number redefined

below is a rendering of the page up to the first error
```

indeed I opened the epub in sigil and:
![image](https://user-images.githubusercontent.com/8254819/101281680-b4254a00-37d0-11eb-9bc2-7f6092651300.png)

are you using pandoc 2.8 or 2.9 ? it seems the bug is fixed in later releases: https://github.com/jgm/pandoc/issues/5986

**Comment by threeplanetssoftware** [comment]
Yes, this is using pandoc 2.9. The fix should be pretty quick, I just do not have the time to test the consequences of that fix to be sure it is safe to submit right now. Below are the offending lines.

https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/blob/3196e6bc1461b1dfa644046ff30ee11789cf416a/.github/workflows/gh-pages.yml#L30-L36
