### ISSUE TITLE
Graphs in PDF not rendering

### ISSUE THREAD

**Issue by jmondo** [webrtc-for-the-curious/webrtc-for-the-curious#72]
Example from page 8 <img width="1239" alt="image" src="https://user-images.githubusercontent.com/603431/106183771-8a93f980-6155-11eb-9497-01ec281f70b2.png">

Amazing resource btw! Even without the graphs ;) 
Got the pdf from https://webrtcforthecurious.com/docs/webrtc-for-the-curious.pdf

**Comment by mogren** [comment]
The images are there now!
